<?php

declare(strict_types=1);

namespace App\Notifications\User;

use Illuminate\Auth\Notifications\ResetPassword;
use Illuminate\Notifications\Messages\MailMessage;

class UserPasswordResetNotification extends ResetPassword
{
    /**
     * 送信URL
     * @param $notifiable
     * @return string
     */
    protected function resetUrl($notifiable): string
    {
        return url(route('admin.password.reset.form', [
            'token' => $this->token,
            'email' => $notifiable->getEmailForPasswordReset(),
        ], false));
    }

    /**
     * メール本文
     * @param $url
     * @return MailMessage
     */
    protected function buildMailMessage($url): MailMessage
    {
        return parent::buildMailMessage($url); // TODO: Change the autogenerated stub
    }
}
