name: PhpUnit Test

on:
  push:
    branches:
      - '**'

jobs:
  laravel-tests:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php: [ 8.2 ]

    services:
      mysql:
        image: mysql:8.0.28
        env:
          MYSQL_DATABASE: laravel_setup_practice_test
          MYSQL_USER: laravel
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      APP_ENV: testing
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: laravel_setup_practice_test
      DB_USERNAME: root
      DB_PASSWORD: root

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: intl, pdo_mysql, exif, pcntl, bcmath
          coverage: pcov

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --no-suggest --optimize-autoloader

      - name: Dump Autoload
        run: composer dump-autoload

      - name: Generate key
        run: php artisan key:generate

      - name: Run database migrations
        run: php artisan migrate

      - name: Install Assets
        run: npm install

      - name: Build Assets
        run: npm run build

      - name: Run the tests
        run: ./vendor/bin/phpunit --coverage-text --colors=auto --display-incomplete

      - name: Run database migrations rollback
        run: php artisan migrate:rollback
